name: Deploy Docker Image To Server
run-name: Deploy Docker Image To Server ğŸ±

on:
  push:
    branches:
      - master # æŒ‡å®šåŠ¨ä½œä¸‹ ä¼šè¿è¡Œ workflow

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # step 1
      - name: Checkout
        uses: actions/checkout@master
      # step 2
      - name: Install and Build ğŸ”§
        run: |
          npm install --force
          npm run build
      # step 3
      - name: Log in to Docker Hub #ç™»é™†docker
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  #dockerçš„ç”¨æˆ·å
          password: ${{ secrets.DOCKER_PASSWORD }}	#dockerçš„å¯†ç 
      # step 4
      - name: Extract metadata (tags, labels) for Docker # è·å–å…ƒæ•°æ®åŒ…æ‹¬tagå’Œlabels
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: nico0408/docker_hub_demo
      # step 5
      - name: Build and push Docker image  #æ„å»ºå’Œå‘å¸ƒ dockeré•œåƒ
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }} #ä¸Šä¸€æ­¥æ‰€æ‹¿åˆ°çš„tagsï¼Œé»˜è®¤æ˜¯åˆ†æ”¯åå­—
          labels: ${{ steps.meta.outputs.labels }} # ä¸Šä¸€æ­¥æ‰€æ‹¿åˆ°çš„labels
      #step 6
      - name: ssh docker login    # ç™»é™†äº‘æœåŠ¡å™¨
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HUAWEI_CLOUD_IP }} #äº‘æœåŠ¡å™¨çš„ip
          username: ${{ secrets.HUAWEI_CLOUD_NAME }} #äº‘æœåŠ¡å™¨çš„ç”¨æˆ·å
          password: ${{ secrets.HUAWEI_CLOUD_PASSWORD }} #äº‘æœåŠ¡å™¨çš„å¯†ç 
          script: cd ~ && sh deploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }} #è¿è¡Œè„šæœ¬




