#referenceï¼š https://www.ruanyifeng.com/blog/2019/09/getting-started-with-github-actions.html
name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push] # æŒ‡å®šåŠ¨ä½œä¸‹ ä¼šè¿è¡Œ workflow
jobs:
  Explore-GitHub-Actions:
    name: My Job
    runs-on: ubuntu-latest # runs-onå­—æ®µæŒ‡å®šè¿è¡Œæ‰€éœ€è¦çš„è™šæ‹Ÿæœºç¯å¢ƒã€‚å®ƒæ˜¯å¿…å¡«å­—æ®µ
    steps:
      # step 1
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Meng
          MIDDLE_NAME: _
          LAST_NAME: Nico
        run: |
         echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
      # step 2
      - name: Checkout
        uses: actions/checkout@master
      # step 3
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          BUILD_SCRIPT: npm install && npm run build
      - run: echo "ğŸ This job's status is ${{ job.status }}."
